import { useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Building2 } from 'lucide-react'
import { Badge, type BadgeVariant } from '@/components/ui/Badge'
import type { ReceiptEditorFormValues } from '@/schemas/receiptEditorSchema'
import './DocumentEditor.css'

export interface ReceiptEditorHeaderProps {
  documentNumber: string
  documentNumberLabel: string
  statusVariant: BadgeVariant
  statusLabel: string
  companyName?: string
  companyAddress?: string
  companyPhone?: string
  companyLogoUrl?: string | null
  customers: { id: number; label: string; phone?: string | null }[]
  invoices: { id: number; label: string }[]
  assignedUserName?: string
  readOnly: boolean
  /** Invoice can only be chosen at create time — once saved, the link is fixed. */
  invoiceLocked: boolean
}

export default function ReceiptEditorHeader({
  documentNumber, documentNumberLabel, statusVariant, statusLabel,
  companyName, companyAddress, companyPhone, companyLogoUrl,
  customers, invoices, assignedUserName, readOnly, invoiceLocked,
}: ReceiptEditorHeaderProps) {
  const { t } = useTranslation()
  const { register, watch, formState: { errors } } = useFormContext<ReceiptEditorFormValues>()
  const selectedCustomerId = watch('customer_id')
  const selectedCustomer = customers.find((c) => c.id === selectedCustomerId)

  return (
    <div className="doc-editor-header">
      <div className="doc-editor-header-company">
        <div className="doc-editor-company-logo">
          {companyLogoUrl ? <img src={companyLogoUrl} alt="" /> : <Building2 size={20} />}
        </div>
        <div>
          <div className="doc-editor-company-name">{companyName || t('common.brandName')}</div>
          {companyAddress && <div className="doc-editor-company-line">{companyAddress}</div>}
          {companyPhone && <div className="doc-editor-company-line">{t('documentEditor.header.telephone')}: {companyPhone}</div>}
        </div>
      </div>

      <div className="doc-editor-header-grid">
        <div className="form-group">
          <label>{t('receipts.editor.invoiceRef')} <span className="required">*</span></label>
          <select
            {...register('invoice_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })}
            disabled={readOnly || invoiceLocked}
          >
            <option value="">{t('receipts.editor.selectInvoice')}</option>
            {invoices.map((inv) => <option key={inv.id} value={inv.id}>{inv.label}</option>)}
          </select>
          {errors.invoice_id && <span className="field-error">{errors.invoice_id.message}</span>}
        </div>
        <div className="form-group">
          <label>{documentNumberLabel}</label>
          <input value={documentNumber || t('documentEditor.header.autoGenerated')} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('common.status')}</label>
          <div style={{ paddingTop: 6 }}>
            <Badge variant={statusVariant}>{statusLabel}</Badge>
          </div>
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.customer')}</label>
          <select {...register('customer_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })} disabled={readOnly}>
            <option value="">{t('documentEditor.header.selectCustomer')}</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.telephone')}</label>
          <input value={selectedCustomer?.phone ?? ''} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.reference')}</label>
          <input {...register('customer_reference')} disabled={readOnly} />
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.salesPerson')}</label>
          <input value={assignedUserName ?? t('common.unassigned')} readOnly disabled />
        </div>
      </div>
    </div>
  )
}
