import { useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Building2 } from 'lucide-react'
import { Badge, type BadgeVariant } from '@/components/ui/Badge'
import type { SalesOrderEditorFormValues } from '@/schemas/salesOrderEditorSchema'
import './DocumentEditor.css'

const CURRENCY_OPTIONS = ['LAK', 'THB', 'USD', 'CNY']

export interface SalesOrderEditorHeaderProps {
  documentNumber: string
  documentNumberLabel: string
  statusVariant: BadgeVariant
  statusLabel: string
  companyName?: string
  companyAddress?: string
  companyPhone?: string
  companyLogoUrl?: string | null
  customers: { id: number; label: string; phone?: string | null; address?: string | null }[]
  quotations: { id: number; label: string }[]
  assignedUserName?: string
  readOnly: boolean
}

export default function SalesOrderEditorHeader({
  documentNumber, documentNumberLabel, statusVariant, statusLabel,
  companyName, companyAddress, companyPhone, companyLogoUrl,
  customers, quotations, assignedUserName, readOnly,
}: SalesOrderEditorHeaderProps) {
  const { t } = useTranslation()
  const { register, watch, formState: { errors } } = useFormContext<SalesOrderEditorFormValues>()
  const selectedCustomerId = watch('customer_id')
  const selectedCustomer = customers.find((c) => c.id === selectedCustomerId)

  return (
    <div className="doc-editor-header">
      <div className="doc-editor-header-company">
        <div className="doc-editor-company-logo">
          {companyLogoUrl ? <img src={companyLogoUrl} alt="" /> : <Building2 size={20} />}
        </div>
        <div>
          <div className="doc-editor-company-name">{companyName || t('common.brandName')}</div>
          {companyAddress && <div className="doc-editor-company-line">{companyAddress}</div>}
          {companyPhone && <div className="doc-editor-company-line">{t('documentEditor.header.telephone')}: {companyPhone}</div>}
        </div>
      </div>

      <div className="doc-editor-header-grid" style={{ gridTemplateColumns: '2fr 1fr' }}>
        <div className="form-group">
          <label>{t('salesOrders.editor.titleLabel')} <span className="required">*</span></label>
          <input {...register('title')} placeholder={t('salesOrders.editor.titlePlaceholder')} disabled={readOnly} />
          {errors.title && <span className="field-error">{errors.title.message}</span>}
        </div>
        <div className="form-group">
          <label>{t('salesOrders.editor.quotationRef')}</label>
          <select
            {...register('quotation_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })}
            disabled={readOnly}
          >
            <option value="">{t('salesOrders.editor.noQuotation')}</option>
            {quotations.map((q) => <option key={q.id} value={q.id}>{q.label}</option>)}
          </select>
        </div>
      </div>

      <div className="doc-editor-header-grid">
        <div className="form-group">
          <label>{t('documentEditor.header.customer')}</label>
          <select {...register('customer_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })} disabled={readOnly}>
            <option value="">{t('documentEditor.header.selectCustomer')}</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.address')}</label>
          <input value={selectedCustomer?.address ?? ''} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.telephone')}</label>
          <input value={selectedCustomer?.phone ?? ''} readOnly disabled />
        </div>

        <div className="form-group">
          <label>{documentNumberLabel}</label>
          <input value={documentNumber || t('documentEditor.header.autoGenerated')} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('salesOrders.editor.orderDate')}</label>
          <input type="date" {...register('order_date')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('salesOrders.editor.expectedDelivery')}</label>
          <input type="date" {...register('expected_delivery_date')} disabled={readOnly} />
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.reference')}</label>
          <input {...register('customer_reference')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.currency')}</label>
          <select {...register('currency')} disabled={readOnly}>
            {CURRENCY_OPTIONS.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.salesPerson')}</label>
          <input value={assignedUserName ?? t('common.unassigned')} readOnly disabled />
        </div>

        <div className="form-group">
          <label>{t('common.status')}</label>
          <div style={{ paddingTop: 6 }}>
            <Badge variant={statusVariant}>{statusLabel}</Badge>
          </div>
        </div>
      </div>
    </div>
  )
}
