"""add geo coordinates to customers, work_orders, and forklifts

Revision ID: d021f0b7f653
Revises: a2b3c4d5e6f7
Create Date: 2026-08-11 01:21:16.769299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd021f0b7f653'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('forklifts', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('forklifts', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('forklifts', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('work_orders', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'longitude')
    op.drop_column('work_orders', 'latitude')
    op.drop_column('forklifts', 'last_location_update')
    op.drop_column('forklifts', 'current_longitude')
    op.drop_column('forklifts', 'current_latitude')
    op.drop_column('customers', 'longitude')
    op.drop_column('customers', 'latitude')
    # ### end Alembic commands ###
