"""add contract quotas and rest policy fields to rental_contracts

Revision ID: f9443692d0dc
Revises: d021f0b7f653
Create Date: 2026-08-13 00:22:16.756123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9443692d0dc'
down_revision: Union[str, Sequence[str], None] = 'd021f0b7f653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default set explicitly on the NOT NULL columns so this backfills
    # existing rows instead of failing against them; matches the Python-side
    # `default=` on the model so new ORM inserts and raw SQL inserts agree.
    op.add_column('rental_contracts', sa.Column('daily_hours_quota', sa.Integer(), nullable=False, server_default='8'))
    op.add_column('rental_contracts', sa.Column('overtime_rate_per_hour', sa.Float(), nullable=True))
    op.add_column('rental_contracts', sa.Column('rest_policy_work_hours', sa.Integer(), nullable=False, server_default='4'))
    op.add_column('rental_contracts', sa.Column('rest_policy_rest_minutes', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('rental_contracts', sa.Column('job_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_contracts', 'job_type')
    op.drop_column('rental_contracts', 'rest_policy_rest_minutes')
    op.drop_column('rental_contracts', 'rest_policy_work_hours')
    op.drop_column('rental_contracts', 'overtime_rate_per_hour')
    op.drop_column('rental_contracts', 'daily_hours_quota')
    # ### end Alembic commands ###
