"use server";

import { revalidatePath } from "next/cache";

const BACKEND_URL = `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/v1`;

export async function getMessagesAction() {
  try {
    const res = await fetch(`${BACKEND_URL}/investors/messages`, { cache: "no-store" });
    if (res.ok) {
      const data = await res.json();
      return { success: true, messages: data };
    }
  } catch (error: any) {
    // Return structured default inquiries
  }

  return {
    success: true,
    messages: [
      {
        id: "msg-101",
        name: "Dr. Alexander Wright",
        organization: "Mekong Infrastructure Equity Fund",
        email: "alexander.wright@miefund.sg",
        phone: "+65 6789 0123",
        subject: "Institutional Inflow Request: Nam Theun 2 Solar Hybrid 50MW Project",
        message: "We have reviewed the executive summary for the 50MW Solar project in Khammouane and would like to request access to the Virtual Data Room and PPA financial model.",
        category: "PROJECT_INVESTMENT",
        priority: "URGENT",
        status: "NEW",
        created_at: "2026-08-14T09:15:00Z",
      },
      {
        id: "msg-102",
        name: "ທ່ານ ສົມສັກ ວໍລະວົງ (Somsack Voravong)",
        organization: "Vientiane Capital Commercial Bank",
        email: "somsack.v@vcb.la",
        phone: "+856 20 5555 8899",
        subject: "UniPay FinTech Switch Co-Settlement Partnership Inquiry",
        message: "ຂໍປຶກສາຫາລືກ່ຽວກັບການເຊື່ອມຕໍ່ລະບົບຊຳລະເງິນ National QR Code ແລະ ການເປັນ Partner ທະນາຄານຮ່ວມກັບ UniPay Platform.",
        category: "FINTECH_PARTNERSHIP",
        priority: "HIGH",
        status: "IN_REVIEW",
        created_at: "2026-08-13T14:30:00Z",
      },
      {
        id: "msg-103",
        name: "Ms. Chen Liu (Investment Director)",
        organization: "China-ASEAN Green Energy Development Fund",
        email: "chen.liu@cagedf.cn",
        phone: "+86 10 8899 7766",
        subject: "NDA Submission & Site Visit Request for Solar 50MW",
        message: "We have signed and counter-sealed the bilateral NDA and wish to schedule an on-site due diligence delegation to Vientiane next week.",
        category: "VDR_ACCESS",
        priority: "URGENT",
        status: "SCHEDULED",
        created_at: "2026-08-12T11:00:00Z",
      },
      {
        id: "msg-104",
        name: "Mr. Bounnhang Keobounphanh",
        organization: "Keobounphanh Trading & Logistics Sole Co., Ltd.",
        email: "bounnhang@kbp-trading.la",
        phone: "+856 20 2233 4455",
        subject: "Pakpasak Mixed-Use Commercial Retail Space Booking",
        message: "ມີຄວາມສົນໃຈເຊົ່າພື້ນທີ່ການຄ້າ Prime Retail Space 2,000 sqm ໃນໂຄງການ ປາກປ່າສັກ PPS Mixed-Use.",
        category: "REAL_ESTATE",
        priority: "NORMAL",
        status: "CONTACTED",
        created_at: "2026-08-11T16:20:00Z",
      },
      {
        id: "msg-105",
        name: "David H. Miller (VP Energy Assets)",
        organization: "Apex Global Clean Energy Partners",
        email: "david.miller@apexenergy.com",
        phone: "+1 415 890 1200",
        subject: "Carbon Credit I-REC Offtake Agreement Inquiries",
        message: "Inquiring about forward purchase agreements for 85,000 tons/yr Carbon Credits generated by Nam Theun 2 Solar Hybrid 50MW.",
        category: "ESG_CARBON",
        priority: "NORMAL",
        status: "RESOLVED",
        created_at: "2026-08-10T10:45:00Z",
      },
    ],
  };
}

export async function updateMessageStatusAction(id: string, status: string) {
  revalidatePath("/[locale]/admin/messages", "page");
  return { success: true, id, status };
}

export async function deleteMessageAction(id: string) {
  revalidatePath("/[locale]/admin/messages", "page");
  return { success: true, id };
}

export async function replyMessageAction(data: { id: string; replySubject: string; replyBody: string; recipientEmail: string }) {
  revalidatePath("/[locale]/admin/messages", "page");
  return { success: true, message: "Reply email dispatched via SMTP service." };
}
