import { useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Building2 } from 'lucide-react'
import { Badge, type BadgeVariant } from '@/components/ui/Badge'
import type { DeliveryNoteEditorFormValues } from '@/schemas/deliveryNoteEditorSchema'
import './DocumentEditor.css'

export interface DeliveryNoteEditorHeaderProps {
  documentNumber: string
  documentNumberLabel: string
  statusVariant: BadgeVariant
  statusLabel: string
  companyName?: string
  companyAddress?: string
  companyPhone?: string
  companyLogoUrl?: string | null
  customers: { id: number; label: string; phone?: string | null }[]
  salesOrders: { id: number; label: string }[]
  assignedUserName?: string
  readOnly: boolean
  /** Sales order can only be chosen at create time — once saved, the link is fixed. */
  salesOrderLocked: boolean
}

export default function DeliveryNoteEditorHeader({
  documentNumber, documentNumberLabel, statusVariant, statusLabel,
  companyName, companyAddress, companyPhone, companyLogoUrl,
  customers, salesOrders, assignedUserName, readOnly, salesOrderLocked,
}: DeliveryNoteEditorHeaderProps) {
  const { t } = useTranslation()
  const { register, watch, formState: { errors } } = useFormContext<DeliveryNoteEditorFormValues>()
  const selectedCustomerId = watch('customer_id')
  const selectedCustomer = customers.find((c) => c.id === selectedCustomerId)

  return (
    <div className="doc-editor-header">
      <div className="doc-editor-header-company">
        <div className="doc-editor-company-logo">
          {companyLogoUrl ? <img src={companyLogoUrl} alt="" /> : <Building2 size={20} />}
        </div>
        <div>
          <div className="doc-editor-company-name">{companyName || t('common.brandName')}</div>
          {companyAddress && <div className="doc-editor-company-line">{companyAddress}</div>}
          {companyPhone && <div className="doc-editor-company-line">{t('documentEditor.header.telephone')}: {companyPhone}</div>}
        </div>
      </div>

      <div className="doc-editor-header-grid">
        <div className="form-group">
          <label>{t('deliveryNotes.editor.salesOrderRef')} <span className="required">*</span></label>
          <select
            {...register('sales_order_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })}
            disabled={readOnly || salesOrderLocked}
          >
            <option value="">{t('deliveryNotes.editor.selectSalesOrder')}</option>
            {salesOrders.map((so) => <option key={so.id} value={so.id}>{so.label}</option>)}
          </select>
          {errors.sales_order_id && <span className="field-error">{errors.sales_order_id.message}</span>}
        </div>
        <div className="form-group">
          <label>{documentNumberLabel}</label>
          <input value={documentNumber || t('documentEditor.header.autoGenerated')} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('common.status')}</label>
          <div style={{ paddingTop: 6 }}>
            <Badge variant={statusVariant}>{statusLabel}</Badge>
          </div>
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.customer')}</label>
          <select {...register('customer_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })} disabled={readOnly}>
            <option value="">{t('documentEditor.header.selectCustomer')}</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.telephone')}</label>
          <input value={selectedCustomer?.phone ?? ''} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('deliveryNotes.editor.deliveryDate')}</label>
          <input type="date" {...register('delivery_date')} disabled={readOnly} />
        </div>

        <div className="form-group">
          <label>{t('deliveryNotes.editor.warehouse')}</label>
          <input {...register('warehouse')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('deliveryNotes.editor.driverName')}</label>
          <input {...register('driver_name')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('deliveryNotes.editor.vehiclePlate')}</label>
          <input {...register('vehicle_plate')} disabled={readOnly} />
        </div>

        <div className="form-group" style={{ gridColumn: '1 / -1' }}>
          <label>{t('deliveryNotes.editor.deliveryAddress')}</label>
          <input {...register('delivery_address')} disabled={readOnly} />
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.reference')}</label>
          <input {...register('customer_reference')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.salesPerson')}</label>
          <input value={assignedUserName ?? t('common.unassigned')} readOnly disabled />
        </div>
      </div>
    </div>
  )
}
