import { useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Building2 } from 'lucide-react'
import { Badge, type BadgeVariant } from '@/components/ui/Badge'
import type { QuotationEditorFormValues } from '@/schemas/quotationEditorSchema'
import './DocumentEditor.css'

const CURRENCY_OPTIONS = ['LAK', 'THB', 'USD', 'CNY']
const QUOTATION_TYPE_OPTIONS = ['rental', 'sales', 'service', 'spare_parts'] as const
// `quotations.type` uses camelCase keys (spareParts) while the backend value is snake_case.
const TYPE_LABEL_KEY: Record<string, string> = {
  rental: 'quotations.type.rental',
  sales: 'quotations.type.sales',
  service: 'quotations.type.service',
  spare_parts: 'quotations.type.spareParts',
}

export interface DocumentEditorHeaderProps {
  documentNumber: string
  documentNumberLabel: string
  statusVariant: BadgeVariant
  statusLabel: string
  companyName?: string
  companyAddress?: string
  companyPhone?: string
  companyLogoUrl?: string | null
  customers: { id: number; label: string; phone?: string | null; address?: string | null }[]
  /** Display-only — reassigning to a different sales person is a future enhancement. */
  assignedUserName?: string
  readOnly: boolean
}

export default function DocumentEditorHeader({
  documentNumber, documentNumberLabel, statusVariant, statusLabel,
  companyName, companyAddress, companyPhone, companyLogoUrl,
  customers, assignedUserName, readOnly,
}: DocumentEditorHeaderProps) {
  const { t } = useTranslation()
  const { register, watch, formState: { errors } } = useFormContext<QuotationEditorFormValues>()
  const selectedCustomerId = watch('customer_id')
  const selectedCustomer = customers.find((c) => c.id === selectedCustomerId)

  return (
    <div className="doc-editor-header">
      <div className="doc-editor-header-company">
        <div className="doc-editor-company-logo">
          {companyLogoUrl ? <img src={companyLogoUrl} alt="" /> : <Building2 size={20} />}
        </div>
        <div>
          <div className="doc-editor-company-name">{companyName || t('common.brandName')}</div>
          {companyAddress && <div className="doc-editor-company-line">{companyAddress}</div>}
          {companyPhone && <div className="doc-editor-company-line">{t('documentEditor.header.telephone')}: {companyPhone}</div>}
        </div>
      </div>

      <div className="doc-editor-header-grid" style={{ gridTemplateColumns: '2fr 1fr' }}>
        <div className="form-group">
          <label>{t('quotations.form.titleLabel')} <span className="required">*</span></label>
          <input {...register('title')} placeholder={t('quotations.form.titlePlaceholder')} disabled={readOnly} />
          {errors.title && <span className="field-error">{errors.title.message}</span>}
        </div>
        <div className="form-group">
          <label>{t('quotations.form.typeLabel')}</label>
          <select {...register('quotation_type')} disabled={readOnly}>
            {QUOTATION_TYPE_OPTIONS.map((v) => (
              <option key={v} value={v}>{t(TYPE_LABEL_KEY[v], v)}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="doc-editor-header-grid">
        <div className="form-group">
          <label>{t('documentEditor.header.customer')}</label>
          <select {...register('customer_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })} disabled={readOnly}>
            <option value="">{t('documentEditor.header.selectCustomer')}</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.address')}</label>
          <input value={selectedCustomer?.address ?? ''} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.telephone')}</label>
          <input value={selectedCustomer?.phone ?? ''} readOnly disabled />
        </div>

        <div className="form-group">
          <label>{documentNumberLabel}</label>
          <input value={documentNumber || t('documentEditor.header.autoGenerated')} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.validFrom')}</label>
          <input type="date" {...register('valid_from')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.validUntil')}</label>
          <input type="date" {...register('valid_until')} disabled={readOnly} />
        </div>

        <div className="form-group">
          <label>{t('documentEditor.header.reference')}</label>
          <input {...register('customer_reference')} disabled={readOnly} />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.currency')}</label>
          <select {...register('currency')} disabled={readOnly}>
            {CURRENCY_OPTIONS.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.salesPerson')}</label>
          <input value={assignedUserName ?? t('common.unassigned')} readOnly disabled />
        </div>

        <div className="form-group">
          <label>{t('common.status')}</label>
          <div style={{ paddingTop: 6 }}>
            <Badge variant={statusVariant}>{statusLabel}</Badge>
          </div>
        </div>
      </div>
    </div>
  )
}
