import { useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Building2 } from 'lucide-react'
import { Badge, type BadgeVariant } from '@/components/ui/Badge'
import type { InvoiceEditorFormValues } from '@/schemas/invoiceEditorSchema'
import './DocumentEditor.css'

const CURRENCY_OPTIONS = ['LAK', 'THB', 'USD', 'CNY']
const REFERENCE_TYPE_OPTIONS: { value: string; labelKey: string }[] = [
  { value: 'sales', labelKey: 'billing.invoice.referenceType.sales' },
  { value: 'work_order', labelKey: 'billing.invoice.referenceType.workOrder' },
  { value: 'rental', labelKey: 'billing.invoice.referenceType.rental' },
]

export interface InvoiceEditorHeaderProps {
  documentNumber: string
  statusVariant: BadgeVariant
  statusLabel: string
  companyName?: string
  companyAddress?: string
  companyPhone?: string
  companyLogoUrl?: string | null
  customers: { id: number; label: string; phone?: string | null; address?: string | null }[]
  /** e.g. "SO-2026-00012 (from QT-2026-00034)" — resolved by the parent page via GET /sales-orders/{id}. */
  linkedSalesOrderLabel?: string | null
  /** Once saved, customer/reference/issue-date/currency are permanently fixed —
   *  InvoiceUpdate does not accept them. Only due_date and exchange_rate stay editable. */
  isNew: boolean
}

export default function InvoiceEditorHeader({
  documentNumber, statusVariant, statusLabel,
  companyName, companyAddress, companyPhone, companyLogoUrl,
  customers, linkedSalesOrderLabel, isNew,
}: InvoiceEditorHeaderProps) {
  const { t } = useTranslation()
  const { register, watch, formState: { errors } } = useFormContext<InvoiceEditorFormValues>()
  const selectedCustomerId = watch('customer_id')
  const selectedCustomer = customers.find((c) => c.id === selectedCustomerId)
  const referenceType = watch('reference_type')
  const currency = watch('currency')

  return (
    <div className="doc-editor-header">
      <div className="doc-editor-header-company">
        <div className="doc-editor-company-logo">
          {companyLogoUrl ? <img src={companyLogoUrl} alt="" /> : <Building2 size={20} />}
        </div>
        <div>
          <div className="doc-editor-company-name">{companyName || t('common.brandName')}</div>
          {companyAddress && <div className="doc-editor-company-line">{companyAddress}</div>}
          {companyPhone && <div className="doc-editor-company-line">{t('documentEditor.header.telephone')}: {companyPhone}</div>}
        </div>
      </div>

      <div className="doc-editor-header-grid">
        <div className="form-group">
          <label>{t('documentEditor.header.customer')} <span className="required">*</span></label>
          <select {...register('customer_id', { setValueAs: (v) => (v === '' ? null : Number(v)) })} disabled={!isNew}>
            <option value="">{t('documentEditor.header.selectCustomer')}</option>
            {customers.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}
          </select>
          {errors.customer_id && <span className="field-error">{errors.customer_id.message}</span>}
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.address')}</label>
          <input value={selectedCustomer?.address ?? ''} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.telephone')}</label>
          <input value={selectedCustomer?.phone ?? ''} readOnly disabled />
        </div>

        <div className="form-group">
          <label>{t('billing.invoice.editor.invoiceNumber')}</label>
          <input value={documentNumber || t('documentEditor.header.autoGenerated')} readOnly disabled />
        </div>
        <div className="form-group">
          <label>{t('billing.invoice.meta.issueDate')}</label>
          <input type="date" {...register('issue_date')} disabled={!isNew} />
        </div>
        <div className="form-group">
          <label>{t('billing.invoice.meta.dueDate')}</label>
          <input type="date" {...register('due_date')} />
        </div>

        <div className="form-group">
          <label>{t('billing.invoice.form.referenceType')}</label>
          <select {...register('reference_type')} disabled={!isNew}>
            {REFERENCE_TYPE_OPTIONS.map((o) => <option key={o.value} value={o.value}>{t(o.labelKey)}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('documentEditor.header.currency')}</label>
          <select {...register('currency')} disabled={!isNew}>
            {CURRENCY_OPTIONS.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>{t('billing.invoice.form.exchangeRate')}</label>
          <input
            type="number" step="0.0001" min="0"
            {...register('exchange_rate', { valueAsNumber: true })}
            disabled={currency === 'LAK'}
          />
        </div>

        {referenceType === 'sales' && (
          <div className="form-group">
            <label>{t('billing.invoice.editor.referenceSalesOrder')}</label>
            <input value={linkedSalesOrderLabel ?? t('billing.invoice.editor.noSalesOrder')} readOnly disabled />
          </div>
        )}
        <div className="form-group">
          <label>{t('common.status')}</label>
          <div style={{ paddingTop: 6 }}>
            <Badge variant={statusVariant}>{statusLabel}</Badge>
          </div>
        </div>
      </div>
    </div>
  )
}
